; generated by Adil - Braille mold maker

;M73 P0 R609
;M73 Q0 S611
;M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
;M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
;M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
;M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
;M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

;TYPE:Custom
;M862.3 P "MK3S" ; printer model check
;M862.1 P0.4 ; nozzle diameter check
;M115 U3.13.3 ; tell printer latest fw version
;G90 ; use absolute coordinates
;G28 W ; home all without mesh bed level
;G80 X80.612 Y66.0709 W91.6428 H91.6253 ; mesh bed levelling


;G1 X220 Y220 F1000 ; go to the first top right corner to start printing

G91 ; use relative coordinates
G21 ; set units to millimeters
M107 ; Fan off
G1 Z3.5 F720

; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
; Dot 1 - 0
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - 0
G1 Y-2.5 F2500
; Dot 6 - *
G1 Z-4.0 F720
G1 Z4.0 F720

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
; Dot 1 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 2 - 0
G1 Y-2.5 F2500
; Dot 3 - 0
G1 X-2.5 Y5 F2500
; Dot 4 - 0
G1 Y-2.5 F2500
; Dot 5 - *
G1 Z-4.0 F720
G1 Z4.0 F720
G1 Y-2.5 F2500
; Dot 6 - 0

; Next character
G1 X-3.5 Y5 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
G1 X-6 F2500
; New line
G1 X210 Y-10 F2500

M204 S1000
;TYPE:Custom

G1 Z50 F720 ; Move print head up
G1 X0 Y200 F3600 ; park

G4 ; wait

M84 ; disable motors